name: docc
description:
  Generate Swift Documentation with help of DocC
author:
  dastrobu
runs:
  using: composite
  steps:
    - name: 'Setup docc'
      shell: bash
      run: dirname $(xcrun --find docc) >> $GITHUB_PATH
    - name: 'Check docc is in path'
      shell: bash
      run: command -v docc
    - name: 'Setup default DOCC_HTML_DIR'
      shell: bash
      run: |
        if [[ -z "$DOCC_HTML_DIR" ]]; then
          export "DOCC_HTML_DIR=$(dirname $(which docc))/../share/docc/render"
          echo "DOCC_HTML_DIR=$DOCC_HTML_DIR" >> $GITHUB_ENV
        fi
        echo "DOCC_HTML_DIR=$DOCC_HTML_DIR"
        if [[ ! -d "$DOCC_HTML_DIR" ]]; then
          echo "DOCC_HTML_DIR points to a non existing directory, please make sure it exists."
          exit 1
        fi
